################################
## External-DNS ServiceAccount
#################################
{{- if .Values.global.rbacEnabled }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ template "external-dns.fullname" . }}
  labels:
    tier: {{ template "external-dns.name" . }}
    chart: {{ template "external-dns.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end }}
