################################
## External-DNS Service
#################################
kind: Service
apiVersion: v1
metadata:
  name: {{ template "external-dns.fullname" . }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
  labels:
    tier: {{ template "external-dns.name" . }}
    component: {{ template "external-dns.name" . }}
    chart: {{ template "external-dns.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
{{- if .Values.service.clusterIP }}
  clusterIP: "{{ .Values.service.clusterIP }}"
{{- end }}
{{- if .Values.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.service.loadBalancerIP }}"
{{- end }}
{{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.service.loadBalancerSourceRanges | indent 4 }}
{{- end }}
  ports:
    - port: {{ .Values.service.servicePort }}
      protocol: TCP
      targetPort: 7979
      name: http
  selector:
    app: {{ template "external-dns.name" . }}
    release: {{ .Release.Name }}
  type: "{{ .Values.service.type }}"
